apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc
spec:
  volumeName: my-azurefile-volume
  accessModes:
    - ReadWriteMany
  storageClassName: "" # default AKS provisioned storage class in my AKS Cluster
  resources:
    requests:
      storage: 5Gi