apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrnk2demo3-deployment
  labels:
    app: acrnk2demo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrnk2demo3
  template:
    metadata:
      labels:
        app: acrnk2demo3
    spec:
      containers:
        - name: acrnk2demo3-vn
          image: acrnk2demo3.azurecr.io/app3/acr-app3:v1 # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acrnk2demo3-secret  
# To schedule pods on Azure Virtual Nodes            
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule            


   