apiVersion: v1
kind: Service
metadata:
  name: acrnk2demo3-loadbalancer-service
  labels:
    app: acrnk2demo3
spec:
  type: LoadBalancer
  selector:
    app: acrnk2demo3
  ports:
    - port: 80
      targetPort: 80
